### ISSUE TITLE
Use array destructuring - when it’s complicated

### ISSUE THREAD

**Issue by ryuran** [20minutes/eslint-config#3]
This line
```javascript
innerContext.color.description = test[3]
```
give this error
```javascript
error  Use array destructuring      prefer-destructuring
```
https://eslint.org/docs/rules/prefer-destructuring

I don’t know how to fix it.

I found a work around, but it’s not fancy

```javascript
const description = test[3]
innerContext.color.description = description
```

**Comment by j0k3r** [comment]
We can disable `array` destructuring regarding https://eslint.org/docs/rules/prefer-destructuring#when-not-to-use-it

**Comment by lethot** [comment]
or maybe something like this
```javascript
[ , , ,innerContext.color.description] = test
```

**Comment by ryuran** [comment]
@lethot I tried it without success.

**Comment by lethot** [comment]
my bad, this messes with the no semi colon rule, you'll have to put a semicolon to your previous line in order to make it work. I guess eslint cannot understand the assignment you do in this line and see it like trying to access a property of the last element appearing in the previous line.

**Comment by lethot** [comment]
but as j0k3r said, you can just disable it for some cases, in this case, I prefer
```javascript
innerContext.color.description = test[3]
```
